### ISSUE TITLE
[FEATURE] Cache options

### ISSUE THREAD

**Issue by jeff9014223** [servusdei2018/shards#34]
**Is your feature request related to a problem? Please describe.**
When running a large discord bot the memory usage sometimes exceed 1 or 2 gigs

**Describe the solution you'd like**
A method or additional options so people can manually pass down cache options

**Describe alternatives you've considered**
I tried using discord directly with goroutines for sharding myself, it does reduce the memory usage to 30mb but I would like to use this library instead of writing my own every time

**Comment by servusdei2018** [comment]
Thanks for bringing this up! I've implemented functionality to disable state tracking automatically, like so:

```go
config := shards.DefaultConfig()
config.StateEnabled = false

mgr, err := shards.NewWithConfig("your-bot-token", config)
if err != nil {
    log.Fatal("error: failed to create manager:", err)
}
```

I hope this helps to reduce your memory consumption, and if you have any other issues/feedback please feel free to bring them up 😄

**Comment by jeff9014223** [comment]
Thanks for the quick implementation!
