### ISSUE TITLE
Handling creation of shards in package instead of user code

### ISSUE THREAD

**Issue by enkeyz** [servusdei2018/shards#8]
Instead manually handling of creating new shards in user code, it would be nice if the package could provide a function, where you pass the number of shards you want, and it returns a shard manager instance with the amount of shards already created.

**Comment by servusdei2018** [comment]
Hmm, after calling `shards.New()`, you can override the amount of shards necessary by setting `mgr.ShardCount` before calling `mgr.Start()`. Doing that should effectively use an arbitrary amount of shards without user code creating them.

**Comment by enkeyz** [comment]
I think it's bad to modify a state like that. I mean, if you have no time to add this feature, I can make a PR.

**Comment by servusdei2018** [comment]
> 
> 
> I think it's bad to modify a state like that. I mean, if you have no time to add this feature, I can make a PR.

Yeah I guess it would be better structured by doing it that way. That would be much appreciated, thank you! 👏🏽

**Comment by enkeyz** [comment]
The main problem here, how to add this feature without breaking people code that depending on this package.

**Comment by servusdei2018** [comment]
> 
> 
> The main problem here, how to add this feature without breaking people code that depending on this package. Because if we just add a numberOfShards parameter to the New function in shard manager, that'll break for people.

I guess a new function could be created, `SetShards(numberOfShards int)`, so that the following would work:

```go
mgr := shards.New("TOKEN").SetShards(4)
```

**Comment by enkeyz** [comment]
Made a PR: https://github.com/servusdei2018/shards/pull/10

**Comment by enkeyz** [comment]
Thanks for taking my suggestion <3

**Comment by servusdei2018** [comment]
Anytime! Thank you for bringing it up too, things like that make the code more ergonomic 😄
