### ISSUE TITLE
Error trying to do restart on example. 

### ISSUE THREAD

**Issue by Bioblaze** [servusdei2018/shards#9]
`discord_1   | [INFO] Restarting shard manager...
discord_1   | panic: runtime error: invalid memory address or nil pointer dereference
discord_1   | [signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0x675519]
discord_1   |
discord_1   | goroutine 60 [running]:
discord_1   | github.com/servusdei2018/shards.(*Manager).Restart(0x0)
discord_1   |   /go/pkg/mod/github.com/servusdei2018/shards@v1.2.1/manager.go:135 +0x39
discord_1   | main.messageCreate(0xc00020aa80, 0xc00012e740)
discord_1   |   /app/main.go:104 +0x233
discord_1   | github.com/bwmarrin/discordgo.messageCreateEventHandler.Handle(0x0, 0x0, {0x6c1ac0, 0xc00012e740})
discord_1   |   /go/pkg/mod/github.com/bwmarrin/discordgo@v0.23.3-0.20210410202908-577e7dd4f6cc/eventhandlers.go:518 +0x38
discord_1   | created by github.com/bwmarrin/discordgo.(*Session).handle
discord_1   |   /go/pkg/mod/github.com/bwmarrin/discordgo@v0.23.3-0.20210410202908-577e7dd4f6cc/event.go:171 +0x172`

**Comment by Bioblaze** [comment]
```
package main

import (
	"fmt"
	"os"
	"os/signal"
	"syscall"

	"github.com/bwmarrin/discordgo"
	"github.com/joho/godotenv"
	"github.com/servusdei2018/shards"
)

var (
	Mgr *shards.Manager
)

func init() {
	err := godotenv.Load(".env")

	if err != nil {
		fmt.Println("Error loading .env file")
	}
}

func main() {
	// Create a new Discord session using the provided bot token.
	Mgr, err := shards.New("Bot " + os.Getenv("BOT_TOKEN"))
	if err != nil {
		fmt.Println("[ERROR] Error creating manager,", err)
		return
	}

	// Register the messageCreate func as a callback for MessageCreate events.
	Mgr.AddHandler(messageCreate)
	// Register the onConnect func as a callback for Connect events.
	Mgr.AddHandler(onConnect)

	// In this example, we only care about receiving message events.
	Mgr.RegisterIntent(discordgo.IntentsGuildMessages)

	fmt.Println("[INFO] Starting shard manager...")

	// Open a websocket connection to Discord and begin listening.
	err = Mgr.Start()
	if err != nil {
		fmt.Println("[ERROR] Error starting manager,", err)
		return
	}

	// Wait here until CTRL-C or other term signal is received.
	fmt.Println("[SUCCESS] Bot is now running.  Press CTRL-C to exit.")
	sc := make(chan os.Signal, 1)
	signal.Notify(sc, syscall.SIGINT, syscall.SIGTERM, os.Interrupt, os.Kill)
	<-sc

	// Cleanly close down the Discord session.
	fmt.Println("[INFO] Stopping shard manager...")

	Mgr.Shutdown()

	fmt.Println("[SUCCESS] Shard manager stopped. Bot is shut down.")
}

// This function will be called (due to AddHandler above) every time one
// of our shards connects.
func onConnect(s *discordgo.Session, evt *discordgo.Connect) {
	fmt.Printf("[INFO] Shard #%v connected.\n", s.ShardID)
}

// This function will be called (due to AddHandler above) every time a
// new  message is created on any channel that the authenticated bot has
// access to.
func messageCreate(s *discordgo.Session, m *discordgo.MessageCreate) {
	// Ignore all messages created by the bot itself.
	// This isn't required in this specific example but it's a good
	// practice.
	if m.Author.ID == s.State.User.ID {
		return
	}

	if m.Content == "test" {
		go test(s, m)
	}
	// If the message is "ping" reply with "Pong!"
	if m.Content == "ping" {
		s.ChannelMessageSend(m.ChannelID, "Pong!")
	}

	// If the message is "pong" reply with "Ping!"
	if m.Content == "pong" {
		s.ChannelMessageSend(m.ChannelID, "Ping!")
	}

	// If the message is "restart" restart the shard manager and rescale
	// if necessary, all with zero down-time.
	if m.Content == "restart" {
		s.ChannelMessageSend(m.ChannelID, "[INFO] Restarting shard manager...")
		fmt.Println("[INFO] Restarting shard manager...")
		if err := Mgr.Restart(); err != nil {
			fmt.Println("[ERROR] Error restarting manager,", err)
		} else {
			s.ChannelMessageSend(m.ChannelID, "[SUCCESS] Manager successfully restarted.")
			fmt.Println("[SUCCESS] Manager successfully restarted.")
		}
	}
}

func test(s *discordgo.Session, m *discordgo.MessageCreate) {
	s.ChannelMessageSend(m.ChannelID, "test!")
}
```

**Comment by servusdei2018** [comment]
@Bioblaze Thanks for the bug report! At the moment I'm short on time so I won't be able to look into this right now, but I'll definitely try to resolve this on Saturday.

**Comment by Bioblaze** [comment]
Your awesome thank you @servusdei2018 <3 ^_^

**Comment by Bioblaze** [comment]
Throw me a line and let me know if you've had a chance to look at it @servusdei2018

**Comment by servusdei2018** [comment]
> 
> 
> Throw me a line and let me know if you've had a chance to look at it @servusdei2018

Hmm, I was unable to duplicate the error. 

The stack trace indicates that the nil pointer dereference is originating on line 104 `fmt.Println("[SUCCESS] Manager successfully restarted.")` which has no pointer references, so the error may originate from a prior version of your source code with some sort of nil pointer dereference there.

**Comment by Bioblaze** [comment]
this is my go.mod file
```
go 1.15

require (
	github.com/bwmarrin/discordgo v0.23.3-0.20210410202908-577e7dd4f6cc
	github.com/caarlos0/env v3.5.0+incompatible // indirect
	github.com/caarlos0/env/v6 v6.7.1 // indirect
	github.com/joho/godotenv v1.3.0 // indirect
	github.com/servusdei2018/shards v1.2.1 // indirect
	golang.org/x/crypto v0.0.0-20210817164053-32db794688a5 // indirect
	golang.org/x/sys v0.0.0-20210910150752-751e447fb3d0 // indirect
)

```

Hope this helps @servusdei2018

**Comment by Bioblaze** [comment]
did you do it with a Bot that only has 1 Shard?

**Comment by Bioblaze** [comment]
I don't get any errors with a Bot that has more then 1 Shard, but i'm developing a new bot. And that lil Guy only has 1 Shard. Maybe that is the issue?

**Comment by servusdei2018** [comment]
> did you do it with a Bot that only has 1 Shard?

Hmm yeah the bot token I pass it is for a bot that's only in one server, so it only gets 1 shard.

**Comment by QWERTIOX** [comment]
Hi, error still occurs, maybe add info about it in the documentation that it occurs with 1 shard and in the example

**Comment by servusdei2018** [comment]
This issue was fixed in a prior version, however it appears that the go package registry was serving an outdated version of the codebase. I have updated the module appropriately. The import path for shards should now be `github.com/servusdei2018/shards/v2`, `github.com/servusdei2018/shards` reverts to v1.2.6 which remains affected by this issue.
